# Generated by Django 3.2.5 on 2021-07-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='fullname',
            field=models.CharField(default='COINxNAME', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='fullname',
            field=models.CharField(default='STOCKxNAME', max_length=200),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
