# Generated by Django 3.2.5 on 2021-07-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20210729_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fullname',
            field=models.CharField(default='STOCKxNAME', max_length=200, null=True),
        ),
    ]
