# Generated by Django 3.2.5 on 2021-08-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_alter_stock_fullname'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_coin',
            field=models.ManyToManyField(blank=True, null=True, to='markets.Coin'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_stock',
            field=models.ManyToManyField(blank=True, null=True, to='markets.Stock'),
        ),
    ]
